# Basic Backlog Analysis Workflow
# Composed workflow using reusable templates for quick analysis

trigger:
- main
- develop

pr:
- main

parameters:
  - name: azureDevOpsOrganization
    displayName: 'Azure DevOps Organization'
    type: string
  
  - name: projectName
    displayName: 'Project Name'
    type: string
  
  - name: customQuery
    displayName: 'Custom WIQL Query (optional)'
    type: string
    default: ''

variables:
  - group: copilot-credentials
  - group: notification-settings

stages:
- template: ../templates/setup-copilot-template.yml
  parameters:
    nodeVersion: '22'
    validationLevel: 'basic'
    maxRetryAttempts: 2
    timeoutSeconds: 180

- template: ../templates/fetch-workitems-template.yml
  parameters:
    azureDevOpsOrganization: ${{ parameters.azureDevOpsOrganization }}
    projectName: ${{ parameters.projectName }}
    wiqlQuery: ${{ coalesce(parameters.customQuery, "SELECT [System.Id], [System.Title], [System.State], [System.AssignedTo], [System.Tags] FROM WorkItems WHERE [System.TeamProject] = '@project' AND [System.State] <> 'Closed' ORDER BY [System.ChangedDate] DESC") }}
    maxResults: 50
    includeDetails: true
    outputFormat: 'standard'
    retryAttempts: 2

- template: ../templates/ai-analysis-template.yml
  parameters:
    analysisMode: 'basic'
    timeoutMinutes: 10
    retryAttempts: 2
    includeMetrics: true
    generateSummary: true
    outputFormat: 'markdown'

- template: ../templates/reporting-template.yml
  parameters:
    reportTitle: 'Basic Backlog Analysis'
    includeCharts: true
    generatePDF: false
    notificationEnabled: true
    sharePointUpload: false
    reportFormats:
      - 'html'
      - 'markdown'